imports:
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }

editor:
    externalPlugins:
        bootstrappackage_table:
            resource: "EXT:bootstrap_package/Resources/Public/CKEditor/Plugins/Table/plugin.min.js"

    config:
        contentsCss: "EXT:template/Resources/Public/dist/css/app.css"

        stylesSet:
            - { name: "Lead", element: "p", attributes: { 'class': 'lead' } }
            - { name: "Small", element: "small" }
            - { name: "Table", element: "table", attributes: { 'class': 'table' } }
            - { name: "Table Kontakt", element: "table", attributes: { 'class': 'table table--contact' } }
            - { name: "Row Active", element: "tr", attributes: { 'class': 'active' } }
            - { name: "Row Success", element: "tr", attributes: { 'class': 'success' } }
            - { name: "Row Info", element: "tr", attributes: { 'class': 'info' } }
            - { name: "Row Warning", element: "tr", attributes: { 'class': 'warning' } }
            - { name: "Row Danger", element: "tr", attributes: { 'class': 'danger' } }


        toolbarGroups:
            - { name: styles, groups: [ format, styles ] }
            - { name: basicstyles, groups: [ basicstyles ] }
            - { name: paragraph, groups: [ list, indent, blocks, align ] }
            - "/"
            - { name: links, groups: [ links ] }
            - { name: clipboard, groups: [ clipboard, cleanup, undo ] }
            - { name: editing, groups: [ spellchecker ] }
            - { name: insert, groups: [ insert ] }
            - { name: tools, groups: [ table, specialchar ] }
            - { name: document, groups: [ mode ] }

        format_tags: "p;h1;h2;h3;h4;h5;pre"

        justifyClasses:
            - text-left
            - text-center
            - text-right
            - text-justify

        extraPlugins:
            - autolink
            - bootstrappackage_table

        removePlugins:
            - image

        removeButtons:
            - Anchor
            - Underline
            - Strike

classesAnchor:
    page:
        class: 'link-page'
        type: 'page'
    folder:
        class: 'link-folder'
        type: 'folder'
    file:
        class: 'link-file'
        type: 'file'
    external:
        class: 'link-external'
        type: 'url'
    mail:
        class: 'link-mail'
        type: 'mail'

buttons:
    link:
        properties:
            class:
                allowedClasses: 'link, link-reset'
