TYPO3:
  CMS:
    Form:
      persistenceManager:
        allowedFileMounts:
          10: 1:/forms/
        allowedExtensionPaths:
          10: EXT:template/Configuration/Resources/Extensions/Form/Forms/
        allowSaveToExtensionPaths: true
        allowDeleteFromExtensionPaths: true

      prototypes:
        standard:
          formElementsDefinition:
            Form:
              renderingOptions:
                templateRootPaths:
                  100: 'EXT:template/Resources/Private/Extensions/Form/Templates/'
                partialRootPaths:
                  100: 'EXT:template/Resources/Private/Extensions/Form/Partials/'
                layoutRootPaths:
                  100: 'EXT:template/Resources/Private/Extensions/Form/Layouts/'

            GridContainer:
              properties:
                elementClassAttribute: 'container'
                # overrules 'GridRow.properties.gridColumnClassAutoConfiguration'
                gridColumnClassAutoConfiguration:
                  gridSize: 12
                  viewPorts:
                    xs:
                      classPattern: 'columns small-{@numbersOfColumnsToUse}'
                    sm:
                      classPattern: 'medium-{@numbersOfColumnsToUse}'
                    md:
                      classPattern: 'large-{@numbersOfColumnsToUse}'
                    lg:
                      classPattern: 'xlarge-{@numbersOfColumnsToUse}'

            GridRow:
              properties:
                elementClassAttribute: 'row order-form-spacer'
                gridColumnClassAutoConfiguration:
                  gridSize: 12
                  viewPorts:
                    xs:
                      classPattern: 'columns small-{@numbersOfColumnsToUse}'
                    sm:
                      classPattern: 'medium-{@numbersOfColumnsToUse}'
                    md:
                      classPattern: 'large-{@numbersOfColumnsToUse}'
                    lg:
                      classPattern: 'xlarge-{@numbersOfColumnsToUse}'
